project:
  type: website
  output-dir: docs

website:
  title: "Powering Change"
  page-navigation: true
  navbar:
    left:
      - href: introduction.qmd
        text: Introduction
      - href: data-sources.qmd
        text: Data Sources
      - href: data-visualization.qmd
        text: Data Visualization
      - href: exploratory-data-analysis.qmd
        text: Exploratory Data Analysis
      - href: univariate-ts-models.qmd
        text: Univariate TS Models (ARIMA/SARIMA)
      - href: multivariate-ts-models.qmd
        text: Multivariate TS Models (ARIMAX/SARIMAX/VAR)
      - href: financial-ts-models.qmd
        text: Financial Time Series Models (ARCH/GARCH)
      - href: deep-learning-ts.qmd
        text: Deep Learning for TS
      - href: other-ts-methods.qmd
        text: "Other: Interrupted TS/ARFIMA/ Spectral Analysis"
      - href: conclusions.qmd
        text: Conclusions

format:
  html:
    theme:
      - lux
      - custom.scss
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    code-fold: true
    code-copy: false
    code-tools: false
    code-overflow: wrap
