project:
  type: website
  output-dir: docs

website:
  title: "Powering Change"
  page-navigation: true
  back-to-top-navigation: true
  search: true
  navbar:
    left:
      - href: introduction.qmd
        text: Intro
      - href: data-sources.qmd
        text: DataSources
      - href: data-visualization.qmd
        text: DataVisualization
      - href: exploratory-data-analysis.qmd
        text: EDA
      - href: univariate-ts-models.qmd
        text: Univariate TS Models
      - href: multivariate-ts-models.qmd
        text: Multivariate TS Models
      - href: financial-ts-models.qmd
        text: Financial TS Models
      - href: deep-learning-ts.ipynb
        text: Deep Learning for TS
      - href: conclusions.qmd
        text: Conclusions

format:
  html:
    theme:
      - lux
      - custom.scss
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    code-fold: true
    code-copy: false
    code-tools: false
    code-overflow: wrap
    page-navigation: true
