<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.548">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Powering Change - Financial Time Series Models (ARCH/GARCH)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Powering Change</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./introduction.html"> 
<span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data-sources.html"> 
<span class="menu-text">Data Sources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data-visualization.html"> 
<span class="menu-text">Data Visualization</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./exploratory-data-analysis.html"> 
<span class="menu-text">EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./univariate-ts-models.html"> 
<span class="menu-text">Univariate TS Models (ARIMA/SARIMA)</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./multivariate-ts-models.html"> 
<span class="menu-text">Multivariate TS Models (ARIMAX/SARIMAX/VAR)</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./financial-ts-models.html" aria-current="page"> 
<span class="menu-text">Financial Time Series Models (ARCH/GARCH)</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./deep-learning-ts.qmd"> 
<span class="menu-text">Deep Learning for TS</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./conclusions.qmd"> 
<span class="menu-text">Conclusions</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1. Introduction</a>
  <ul class="collapse">
  <li><a href="#exxon-mobil-corporation-and-its-market-influence" id="toc-exxon-mobil-corporation-and-its-market-influence" class="nav-link" data-scroll-target="#exxon-mobil-corporation-and-its-market-influence">Exxon Mobil Corporation and its Market Influence</a></li>
  <li><a href="#chevron-corporation-and-its-economic-role" id="toc-chevron-corporation-and-its-economic-role" class="nav-link" data-scroll-target="#chevron-corporation-and-its-economic-role">Chevron Corporation and its Economic Role</a></li>
  <li><a href="#analytical-approach-using-arch-and-garch-models" id="toc-analytical-approach-using-arch-and-garch-models" class="nav-link" data-scroll-target="#analytical-approach-using-arch-and-garch-models">Analytical Approach Using ARCH and GARCH Models</a></li>
  </ul></li>
  <li><a href="#plot-the-data" id="toc-plot-the-data" class="nav-link" data-scroll-target="#plot-the-data">2. Plot the Data</a></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model">3. Fitting the Model</a></li>
  <li><a href="#acfpacf-plots" id="toc-acfpacf-plots" class="nav-link" data-scroll-target="#acfpacf-plots">4. ACF/PACF Plots</a>
  <ul class="collapse">
  <li><a href="#returns" id="toc-returns" class="nav-link" data-scroll-target="#returns">4.1 Returns</a></li>
  <li><a href="#absolute-returns" id="toc-absolute-returns" class="nav-link" data-scroll-target="#absolute-returns">4.2 Absolute Returns</a></li>
  <li><a href="#squared-returns" id="toc-squared-returns" class="nav-link" data-scroll-target="#squared-returns">4.3 Squared Returns</a></li>
  </ul></li>
  <li><a href="#arch-test" id="toc-arch-test" class="nav-link" data-scroll-target="#arch-test">5. ARCH Test</a></li>
  <li><a href="#fitting-arima-model" id="toc-fitting-arima-model" class="nav-link" data-scroll-target="#fitting-arima-model">6. Fitting ARIMA model</a></li>
  <li><a href="#analyising-the-residuals" id="toc-analyising-the-residuals" class="nav-link" data-scroll-target="#analyising-the-residuals">7. Analyising the Residuals</a></li>
  <li><a href="#method-1-garch-model-on-arima-residuals" id="toc-method-1-garch-model-on-arima-residuals" class="nav-link" data-scroll-target="#method-1-garch-model-on-arima-residuals">8. Method 1: GARCH Model on ARIMA Residuals</a></li>
  <li><a href="#method-2-garch-model" id="toc-method-2-garch-model" class="nav-link" data-scroll-target="#method-2-garch-model">9. Method 2: GARCH Model</a></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">10. Model Diagnostics</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation">11. Cross-Validation</a></li>
  <li><a href="#final-model" id="toc-final-model" class="nav-link" data-scroll-target="#final-model">12. Final Model</a></li>
  <li><a href="#forecasting-with-the-final-model" id="toc-forecasting-with-the-final-model" class="nav-link" data-scroll-target="#forecasting-with-the-final-model">13. Forecasting with the Final Model</a></li>
  <li><a href="#volatility-plot" id="toc-volatility-plot" class="nav-link" data-scroll-target="#volatility-plot">14. Volatility Plot</a></li>
  <li><a href="#model-equations" id="toc-model-equations" class="nav-link" data-scroll-target="#model-equations">15. Model Equations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Financial Time Series Models (ARCH/GARCH)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<p>In this section of our project, we will analyze financial time series data related to key players in the energy market, specifically Exxon Mobil Corporation (XOM) and Chevron Corporation (CVX). These companies, pivotal in the global energy landscape, not only reflect the economic pulses of the oil industry but also provide insights into how shifts in energy policies and market dynamics influence significant economic indicators.</p>
<section id="exxon-mobil-corporation-and-its-market-influence" class="level3">
<h3 class="anchored" data-anchor-id="exxon-mobil-corporation-and-its-market-influence">Exxon Mobil Corporation and its Market Influence</h3>
<p>Exxon Mobil, a titan in the oil industry, has been at the forefront of energy production and innovation. The company’s activities span across the extraction, refining, and distribution of energy products, positioning it as a critical barometer for assessing the economic health and trends within the energy sector. By examining the financial time series of Exxon Mobil’s stock prices, we aim to capture the volatility and market sentiment that underpin the broader economic implications of shifts in oil prices and energy policies.</p>
</section>
<section id="chevron-corporation-and-its-economic-role" class="level3">
<h3 class="anchored" data-anchor-id="chevron-corporation-and-its-economic-role">Chevron Corporation and its Economic Role</h3>
<p>Similarly, Chevron, as a major competitor and another influential player in the oil market, offers a complementary perspective to the economic analysis of the energy sector. Chevron’s extensive operations in energy production and its strategic responses to global energy demands make its financial performance a valuable indicator of the sector’s economic stability and growth. The analysis of Chevron’s stock price volatility will help us understand how energy market fluctuations and transitions toward renewable resources impact major energy corporations.</p>
</section>
<section id="analytical-approach-using-arch-and-garch-models" class="level3">
<h3 class="anchored" data-anchor-id="analytical-approach-using-arch-and-garch-models">Analytical Approach Using ARCH and GARCH Models</h3>
<p>To conduct the time series analysis of financial data from Exxon Mobil and Chevron, we will utilize ARCH (Autoregressive Conditional Heteroskedasticity) and GARCH (Generalized Autoregressive Conditional Heteroskedasticity) models. These models are particularly effective for financial market data as they adeptly handle the inherent volatility typical of stock return data. By examining the volatility patterns in the stock prices of XOM and CVX, we aim to glean insights into how market dynamics, driven by both traditional and renewable energy sources, are shaping the economic narratives of these leading corporations.</p>
<p>In this detailed exploration, our objective is to uncover how historical and present economic conditions, policy shifts, and global energy crises influence the financial trajectories of key energy players. These insights will not only deepen our understanding of the energy sector’s impact on global economics but also aid in formulating strategies for a sustainable energy future.</p>
</section>
</section>
<section id="plot-the-data" class="level1">
<h1>2. Plot the Data</h1>
<p>To visually analyze the stock price trends of Exxon Mobil and Chevron Corporation, we will employ the quantmod package to fetch and plot the data.</p>
<p>Graphical representations provide intuitive insights into the financial performance over time, highlighting trends, volatilities, and anomalies that might not be immediately apparent from raw data</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the stock prices</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chartSeries</span>(Exxon_stockprice, <span class="at">theme =</span> <span class="fu">chartTheme</span>(<span class="st">"white"</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">bar.type =</span> <span class="st">"hlc"</span>,  </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">up.col =</span> <span class="st">"green"</span>,  </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">dn.col =</span> <span class="st">"red"</span>) </span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The chart shows the stock price movement for Exxon Mobil Corporation from January 1990 to April 2024. The data, represented through a high-low-close (HLC) bar chart, shows trajectory of prices over more than three decades. A general uptrend can be observed in the late ’90s, followed by increased volatility and several peaks and dips that suggest fluctuating market conditions through the 2000s and 2010s. The trading volume, in the histogram below the main price chart, offers a narrative on market sentiment, with spikes in volume associated with changes in the industry.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the stock prices</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chartSeries</span>(Chevron_stockprice, <span class="at">theme =</span> <span class="fu">chartTheme</span>(<span class="st">"white"</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">bar.type =</span> <span class="st">"hlc"</span>,  </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">up.col =</span> <span class="st">"green"</span>,  </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">dn.col =</span> <span class="st">"red"</span>) </span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The chart displays Chevron Corporation’s stock prices from 1990 to April 2024, capturing significant ups and downs that reflect key changes in the energy industry and wider economic trends. The green and red bars indicates when prices went up or down each day. After a clear rise in prices until the late ’90s, the stock experiences noticeable volatility, swinging up and down.</p>
<p>The histogram below the chart, which tracks trading volume, aligns with notable shifts in stock prices, suggesting times when investors were particularly active. This visualization lays the groundwork for a detailed examination of price volatility using ARCH/GARCH models, offering a visual summary of the market forces that have influenced Chevron’s stock over the years.</p>
</div>
</div>
</div>
</section>
<section id="fitting-the-model" class="level1">
<h1>3. Fitting the Model</h1>
<p>Now, we will move forward to fit an ARCH/GARCH model to the stock price data. The first step in this process is to prepare the time series by calculating the stock price returns, which are typically used in financial time series modeling because they are more likely to exhibit stationary properties—a key requirement for ARCH/GARCH models.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to a time series object</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Exxon_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(Exxon_stockprice<span class="sc">$</span>XOM.Adjusted, <span class="at">start=</span><span class="fu">decimal_date</span>(<span class="fu">as.Date</span>(<span class="st">"1990-01-01"</span>)), <span class="at">frequency =</span> <span class="fl">365.25</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate log returns</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>returns_exxon <span class="ot">&lt;-</span> <span class="fu">log</span>(Exxon_ts)<span class="sc">%&gt;%</span> <span class="fu">diff</span>()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">summary</span>(returns_exxon))</span></code></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">XOM.Adjusted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. :-0.1502715</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.:-0.0076625</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median : 0.0001236</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean : 0.0003926</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.: 0.0085811</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. : 0.1586308</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the summary statistics, we can clearly see that the mean return is close to zero, but with significant deviation. This is characteristic of financial data, where over long periods, the mean return tends to be small. This behavior of returns—small and steady on average, with occasional bursts of high variation—is precisely what ARCH/GARCH models aim to capture and quantify.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the returns</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(returns_exxon, <span class="at">color=</span><span class="st">"dodgerblue3"</span>) <span class="sc">+</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Exxon Mobil Stock Price Returns"</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows the daily returns on Exxon Mobil’s stock from 1990 to 2024. The returns, calculated using logarithmic differences, fluctuate around zero, with spikes that indicate days of particularly high volatility. The distribution of returns is fairly symmetric, there is volatility clustering in the returns.</p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to a time series object</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Chevron_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(Chevron_stockprice<span class="sc">$</span>CVX.Adjusted, <span class="at">start=</span><span class="fu">decimal_date</span>(<span class="fu">as.Date</span>(<span class="st">"1990-01-01"</span>)), <span class="at">frequency =</span> <span class="fl">365.25</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate log returns</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>returns_chevron <span class="ot">&lt;-</span> <span class="fu">log</span>(Chevron_ts)<span class="sc">%&gt;%</span> <span class="fu">diff</span>()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">summary</span>(returns_chevron))</span></code></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">CVX.Adjusted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. :-0.2500622</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.:-0.0079805</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median : 0.0004278</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean : 0.0004088</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.: 0.0089683</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. : 0.2049039</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The summary statistics for Chevron’s returns highlight a median value slightly above zero, suggesting that half of the observed returns were positive over the long term. However, the minimum and maximum values point to significant swings in the stock’s performance.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the returns</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(returns_chevron, <span class="at">color=</span><span class="st">"dodgerblue3"</span>) <span class="sc">+</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Chevron Stock Price Returns"</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plotted returns of Chevron’s stock, similar to Exxon Mobil’s, show clusters of volatility. These clusters where the spikes are denser indicate periods of heightened uncertainty or market activity. This pattern is a key feature that the forthcoming ARCH/GARCH analysis will aim to capture.</p>
</div>
</div>
</div>
</section>
<section id="acfpacf-plots" class="level1">
<h1>4. ACF/PACF Plots</h1>
<p>To further investigate the nature of the stock price returns and prepare for ARCH/GARCH modeling, it’s essential to look at the autocorrelations.</p>
<p>Autocorrelation Function (ACF) and Partial Autocorrelation Function (PACF) plots help us identify whether returns are influenced by their own past values (autocorrelation) and to what extent (partial autocorrelation). This step is key in determining the appropriate lag order for the ARCH/GARCH models.</p>
<section id="returns" class="level2">
<h2 class="anchored" data-anchor-id="returns">4.1 Returns</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ACF Plot for Exxon Mobil Stock</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Exxon_acf <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(returns_exxon,<span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"ACF Plot for Exxon Mobil Returns "</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#PACF Plot for Exxon Mobil Stock</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>Exxon_pacf <span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(returns_exxon,<span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"PACF Plot for Exxon Mobil Returns"</span>) <span class="sc">+</span> </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(Exxon_acf, Exxon_pacf, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Upon examining the ACF and PACF plots we can see values quickly drop off and mostly lie within the significance bounds, the returns appear to be stationary. Possible q and p values would be q = 0, 1, 2 and p = 0, 1, 2</p>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ACF Plot for Chevron Stock</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>Chevron_acf <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(returns_chevron,<span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"ACF Plot for Chevron Stock Returns"</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co">#PACF Plot for Chevron Stock</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>Chevron_pacf <span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(returns_chevron,<span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"PACF Plot for Chevron Stock Returns"</span>) <span class="sc">+</span> </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(Chevron_acf, Chevron_pacf, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Upon examining the ACF and PACF plots we can see values quickly drop off and mostly lie within the significance bounds, the returns appear to be stationary. Possible q and p values would be q = 0, 1 and p = 0, 1</p>
</div>
</div>
</div>
</section>
<section id="absolute-returns" class="level2">
<h2 class="anchored" data-anchor-id="absolute-returns">4.2 Absolute Returns</h2>
<p>The ACF and PACF plots for the absolute returns give us insights into the nature of volatility in the stock’s returns. When we analyze absolute returns, we’re focusing on the magnitude of changes, regardless of direction, which can often reveal volatility patterns.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ACF Plot for Exxon Mobil Stock</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>Exxon_acf_abs <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(<span class="fu">abs</span>(returns_exxon),<span class="at">lag.max=</span><span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"ACF Plot for Exxon Mobil Absolute Returns"</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">#PACF Plot for Exxon Mobil Stock</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>Exxon_pacf_abs <span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(<span class="fu">abs</span>(returns_exxon),<span class="at">lag.max=</span><span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"PACF Plot for Exxon Mobil Absolute Returns"</span>) <span class="sc">+</span> </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(Exxon_acf_abs, Exxon_pacf_abs, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The ACF plot for the absolute returns shows significant autocorrelation across several lags, this indicates persistent volatility in the stock price returns. This is also indicative of the volatility clustering seen in financial time series.</p>
<p>The PACF plot shows significant correlations at the early lags (from 1 to 11, then at 17 and 18). After these initial lags, the correlations in the PACF plot decrease and generally stay within the confidence interval</p>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ACF Plot for Chevron Stock</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Chevron_acf_abs <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(<span class="fu">abs</span>(returns_chevron),<span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"ACF Plot for Chevron Stock Absolute Returns"</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">#PACF Plot for Chevron Stock</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>Chevron_pacf_abs <span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(<span class="fu">abs</span>(returns_chevron),<span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"PACF Plot for Chevron Stock Absolute Returns"</span>) <span class="sc">+</span> </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(Chevron_acf_abs, Chevron_pacf_abs, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="squared-returns" class="level2">
<h2 class="anchored" data-anchor-id="squared-returns">4.3 Squared Returns</h2>
<p>Examining squared returns is a technique in time series analysis to assess volatility patterns. When returns are squared, patterns in volatility might become more evident, as periods of high volatility will result in higher squared returns. These patterns are crucial for ARCH/GARCH models.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ACF Plot for Exxon Mobil Squared Returns</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>Exxon_acf_se <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(returns_exxon<span class="sc">^</span><span class="dv">2</span>, <span class="at">lag.max=</span><span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"ACF Plot for Exxon Mobil Squared Returns"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># PACF Plot for Exxon Mobil Squared Returns</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>Exxon_pacf_se <span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(returns_exxon<span class="sc">^</span><span class="dv">2</span>, <span class="at">lag.max=</span><span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"PACF Plot for Exxon Mobil Squared Returns"</span>) <span class="sc">+</span> </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange the plots on a grid</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(Exxon_acf_se, Exxon_pacf_se, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The ACF plot for squared returns shows a much slower decay, indicating that volatility shocks have a long-lasting effect. The ACF plot here suggests that volatility shocks to Exxon Mobil’s stock prices are persistent, with a high level of autocorrelation extending across many lags.</p>
<p>The PACF plot for squared returns, while also showing some significant lags, doesn’t carry the same pattern of persistence as the ACF.</p>
<p>This persistence of volatility as indicated by the squared returns ACF and PACF plots reinforces the need for a GARCH model in capturing the time-varying volatility in the stock returns</p>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ACF Plot for Chevron Stock</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Chevron_acf_se <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(returns_chevron<span class="sc">^</span><span class="dv">2</span>,<span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"ACF Plot for Chevron Stock Squared Returns"</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#PACF Plot for Chevron Stock</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>Chevron_pacf_se <span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(returns_chevron<span class="sc">^</span><span class="dv">2</span>,<span class="dv">40</span>) <span class="sc">+</span> </span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"PACF Plot for Chevron Stock Squared Returns"</span>) <span class="sc">+</span> </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(Chevron_acf_se, Chevron_pacf_se, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="arch-test" class="level1">
<h1>5. ARCH Test</h1>
<p>Before fitting an ARCH or GARCH model, it is important to formally test for the presence of ARCH effects that is, to test whether there are autoregressive conditional heteroskedasticity features in the time series data.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct the ARCH test</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ArchTest</span>(returns_exxon, <span class="at">lags=</span><span class="dv">1</span>, <span class="at">demean=</span><span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    ARCH LM-test; Null hypothesis: no ARCH effects

data:  returns_exxon
Chi-squared = 590.35, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The result of the ARCH test indicates a Chi-squared statistic of 590.35 with 1 degree of freedom and a p-value less than 2.2e-16, which is extremely low. This leads us to reject the null hypothesis of no ARCH effects. There is very strong evidence of autoregressive conditional heteroskedasticity in the Exxon Mobil stock returns.</p>
<p>Given these results, it is appropriate to proceed with fitting an ARCH/GARCH model to Exxon Mobil’s stock returns to better understand and predict the volatility patterns.</p>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ArchTest</span>(returns_chevron, <span class="at">lags=</span><span class="dv">1</span>, <span class="at">demean=</span><span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    ARCH LM-test; Null hypothesis: no ARCH effects

data:  returns_chevron
Chi-squared = 260.57, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="fitting-arima-model" class="level1">
<h1>6. Fitting ARIMA model</h1>
<p>When volatility clustering is present, as indicated by the ARCH test, it’s good practice to first model the mean of the time series. An ARIMA model helps in capturing the autocorrelation in the mean of the series. Once we’ve accounted for any autocorrelation in the mean with the ARIMA model, we can proceed to model the conditional variance (volatility) using GARCH models.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<p>To find the best ARIMA model, we search across different combinations of p (autoregressive terms), d (differencing terms), and q (moving average terms), and select the model with the lowest information criteria (AIC, BIC, and AICc).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ARIMA.c<span class="ot">=</span><span class="cf">function</span>(p1,p2,q1,q2,data){</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>temp<span class="ot">=</span><span class="fu">c</span>()</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co">#d=1</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>i<span class="ot">=</span><span class="dv">1</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>temp<span class="ot">=</span> <span class="fu">data.frame</span>()</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>ls<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NA</span>,<span class="dv">6</span><span class="sc">*</span><span class="dv">18</span>),<span class="at">nrow=</span><span class="dv">18</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (p <span class="cf">in</span> p1<span class="sc">:</span>p2)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(q <span class="cf">in</span> q1<span class="sc">:</span>q2)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  {</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span>(d <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span>(p<span class="sc">+</span>d<span class="sc">+</span>q<span class="sc">&lt;=</span><span class="dv">6</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>      {</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>        model<span class="ot">&lt;-</span> <span class="fu">Arima</span>(data,<span class="at">order=</span><span class="fu">c</span>(p,d,q))</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>        ls[i,]<span class="ot">=</span> <span class="fu">c</span>(p,d,q,model<span class="sc">$</span>aic,model<span class="sc">$</span>bic,model<span class="sc">$</span>aicc)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>        i<span class="ot">=</span>i<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>temp<span class="ot">=</span> <span class="fu">as.data.frame</span>(ls)</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(temp)<span class="ot">=</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"d"</span>,<span class="st">"q"</span>,<span class="st">"AIC"</span>,<span class="st">"BIC"</span>,<span class="st">"AICc"</span>)</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>temp</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">ARIMA.c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">2</span>,<span class="at">data=</span>returns_exxon) </span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>output</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   p d q       AIC       BIC      AICc
1  0 0 0 -47296.18 -47282.05 -47296.18
2  0 1 0 -40683.01 -40675.95 -40683.01
3  0 0 1 -47347.75 -47326.56 -47347.75
4  0 1 1 -47280.64 -47266.51 -47280.64
5  0 0 2 -47370.17 -47341.91 -47370.16
6  0 1 2 -47332.04 -47310.84 -47332.04
7  1 0 0 -47341.95 -47320.75 -47341.95
8  1 1 0 -43299.59 -43285.46 -43299.59
9  1 0 1 -47373.03 -47344.77 -47373.03
10 1 1 1 -47326.26 -47305.07 -47326.26
11 1 0 2 -47371.46 -47336.13 -47371.45
12 1 1 2 -47356.93 -47328.67 -47356.92
13 2 0 0 -47366.91 -47338.65 -47366.90
14 2 1 0 -44522.54 -44501.35 -44522.54
15 2 0 1 -47371.37 -47336.05 -47371.36
16 2 1 1 -47351.11 -47322.85 -47351.11
17 2 0 2 -47370.15 -47327.76 -47370.14
18 2 1 2 -47355.50 -47320.17 -47355.49</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>output[<span class="fu">which.min</span>(output<span class="sc">$</span>AIC),] </span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  p d q       AIC       BIC      AICc
9 1 0 1 -47373.03 -47344.77 -47373.03</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>output[<span class="fu">which.min</span>(output<span class="sc">$</span>BIC),] </span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  p d q       AIC       BIC      AICc
9 1 0 1 -47373.03 -47344.77 -47373.03</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>output[<span class="fu">which.min</span>(output<span class="sc">$</span>AICc),] </span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  p d q       AIC       BIC      AICc
9 1 0 1 -47373.03 -47344.77 -47373.03</code></pre>
</div>
</div>
<p>The best ARIMA model according to the lowest AIC, BIC and AICC is ARIMA(1,0,1)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>fit_exxon <span class="ot">&lt;-</span> <span class="fu">Arima</span>(returns_exxon,<span class="at">order=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_exxon)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Series: returns_exxon 
ARIMA(1,0,1) with non-zero mean 

Coefficients:
         ar1      ma1   mean
      0.5315  -0.6136  4e-04
s.e.  0.0723   0.0673  1e-04

sigma^2 = 0.000244:  log likelihood = 23690.52
AIC=-47373.03   AICc=-47373.03   BIC=-47344.77

Training set error measures:
                        ME       RMSE        MAE MPE MAPE      MASE        ACF1
Training set -2.384065e-06 0.01561831 0.01100162 NaN  Inf 0.6700628 0.001893208</code></pre>
</div>
</div>
<p>The standard errors are relatively small compared to the coefficients, suggesting that the coefficients are likely to be significantly different from zero.</p>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ARIMA.c<span class="ot">=</span><span class="cf">function</span>(p1,p2,q1,q2,data){</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>temp<span class="ot">=</span><span class="fu">c</span>()</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>d<span class="ot">=</span><span class="dv">1</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>i<span class="ot">=</span><span class="dv">1</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>temp<span class="ot">=</span> <span class="fu">data.frame</span>()</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>ls<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NA</span>,<span class="dv">6</span><span class="sc">*</span><span class="dv">18</span>),<span class="at">nrow=</span><span class="dv">18</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (p <span class="cf">in</span> p1<span class="sc">:</span>p2)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(q <span class="cf">in</span> q1<span class="sc">:</span>q2)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  {</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span>(d <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span>(p<span class="sc">+</span>d<span class="sc">+</span>q<span class="sc">&lt;=</span><span class="dv">6</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>      {</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>        model<span class="ot">&lt;-</span> <span class="fu">Arima</span>(data,<span class="at">order=</span><span class="fu">c</span>(p,d,q))</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>        ls[i,]<span class="ot">=</span> <span class="fu">c</span>(p,d,q,model<span class="sc">$</span>aic,model<span class="sc">$</span>bic,model<span class="sc">$</span>aicc)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>        i<span class="ot">=</span>i<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>temp<span class="ot">=</span> <span class="fu">as.data.frame</span>(ls)</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(temp)<span class="ot">=</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"d"</span>,<span class="st">"q"</span>,<span class="st">"AIC"</span>,<span class="st">"BIC"</span>,<span class="st">"AICc"</span>)</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>temp</span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">ARIMA.c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">2</span>,<span class="at">data=</span>returns_chevron) </span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>output</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   p d q       AIC       BIC      AICc
1  0 0 0 -46406.59 -46392.46 -46406.59
2  0 1 0 -39788.46 -39781.40 -39788.46
3  0 0 1 -46454.39 -46433.19 -46454.38
4  0 1 1 -46391.15 -46377.03 -46391.15
5  0 0 2 -46453.61 -46425.35 -46453.60
6  0 1 2 -46438.72 -46417.53 -46438.72
7  1 0 0 -46452.96 -46431.76 -46452.95
8  1 1 0 -42629.60 -42615.47 -42629.59
9  1 0 1 -46453.75 -46425.49 -46453.74
10 1 1 1 -46437.37 -46416.18 -46437.37
11 1 0 2 -46451.60 -46416.28 -46451.59
12 1 1 2 -46438.04 -46409.78 -46438.03
13 2 0 0 -46453.49 -46425.23 -46453.49
14 2 1 0 -43806.11 -43784.91 -43806.10
15 2 0 1 -46451.51 -46416.18 -46451.50
16 2 1 1 -46437.88 -46409.62 -46437.87
17 2 0 2 -46449.84 -46407.46 -46449.83
18 2 1 2 -46436.18 -46400.86 -46436.17</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>output[<span class="fu">which.min</span>(output<span class="sc">$</span>AIC),] </span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  p d q       AIC       BIC      AICc
3 0 0 1 -46454.39 -46433.19 -46454.38</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>output[<span class="fu">which.min</span>(output<span class="sc">$</span>BIC),] </span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  p d q       AIC       BIC      AICc
3 0 0 1 -46454.39 -46433.19 -46454.38</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>output[<span class="fu">which.min</span>(output<span class="sc">$</span>AICc),] </span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  p d q       AIC       BIC      AICc
3 0 0 1 -46454.39 -46433.19 -46454.38</code></pre>
</div>
</div>
<p>The best ARIMA model according to the lowest AIC is ARIMA(0,0,1)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>fit_chevron <span class="ot">&lt;-</span> <span class="fu">Arima</span>(returns_chevron,<span class="at">order=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_chevron)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Series: returns_chevron 
ARIMA(0,0,1) with non-zero mean 

Coefficients:
          ma1   mean
      -0.0769  4e-04
s.e.   0.0109  2e-04

sigma^2 = 0.0002714:  log likelihood = 23230.19
AIC=-46454.39   AICc=-46454.38   BIC=-46433.19

Training set error measures:
                        ME       RMSE        MAE MPE MAPE      MASE
Training set -3.755846e-08 0.01647249 0.01143942 NaN  Inf 0.6712263
                     ACF1
Training set 0.0008956264</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="analyising-the-residuals" class="level1">
<h1>7. Analyising the Residuals</h1>
<p>After fitting an ARIMA(1,0,1) model to the Exxon Mobil returns, we need to analyze the residuals to ensure that the model has captured the data’s structure adequately. This step is crucial because any pattern left in the residuals can indicate that the model hasn’t fully captured the underlying process.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>model_output_e <span class="ot">&lt;-</span> <span class="fu">capture.output</span>(<span class="fu">sarima</span>(returns_exxon,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model_output_e</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(model_output_e[<span class="dv">22</span><span class="sc">:</span><span class="dv">34</span>], model_output_e[<span class="fu">length</span>(model_output_e)], <span class="at">sep =</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>) </span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>converged
&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;
 
Coefficients: 
      Estimate     SE t.value p.value
ar1     0.5315 0.0723  7.3550  0.0000
ma1    -0.6136 0.0673 -9.1150  0.0000
xmean   0.0004 0.0001  2.8431  0.0045

sigma^2 estimated as 0.0002439316 on 8642 degrees of freedom 
 
AIC = -5.479819  AICc = -5.479818  BIC = -5.47655 
 
 </code></pre>
</div>
</div>
<p>The Standardized Residuals plot does show some volatility left, just before 2000, between 2003 and 2004 and around 2010 to 2011. These spikes indicate that the ARIMA model may not have fully captured the variability during these periods.</p>
<p>The coefficient estimates and their corresponding standard errors, t-values, and p-values confirm the significance of the AR1 and MA1 terms.</p>
<p>Moving forward with the analysis, after fitting an ARIMA(1,0,1) model, we will now examine the autocorrelation in both the residuals and the squared residuals. This step is crucial as it helps us to understand the nature of the residuals and assess whether a GARCH model is necessary.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>exxon.res<span class="ot">&lt;-</span>fit_exxon<span class="sc">$</span>residuals</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(exxon.res, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>plot2<span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(exxon.res, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(plot1, plot2,<span class="at">nrow=</span><span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The autocorrelations appear to be within the confidence bands for most lags, suggesting there is no significant autocorrelation remaining in the residuals. Similarly, the PACF shows that the partial autocorrelations are also within the confidence bounds for most of the lags</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(exxon.res<span class="sc">^</span><span class="dv">2</span>, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>plot4<span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(exxon.res<span class="sc">^</span><span class="dv">2</span>, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(plot3, plot4,<span class="at">nrow=</span><span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The slow decay in autocorrelation across lags indicates that there is high volatility clustering. The PACF plot also shows some spikes at early lags, suggesting that there is some volatility.</p>
<p>These plots are indicative of conditional heteroskedasticity in the series, which is not captured by the ARIMA model. It is recommended to proceed with fitting a GARCH model. The significant ACF in the squared residuals indicates that a GARCH(1,1) model is appropriate.</p>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sarima</span>(returns_chevron,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>initial  value -4.103183 
iter   2 value -4.106061
iter   3 value -4.106063
iter   3 value -4.106063
iter   3 value -4.106063
final  value -4.106063 
converged
initial  value -4.106063 
iter   1 value -4.106063
final  value -4.106063 
converged
&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;
 
Coefficients: 
      Estimate     SE t.value p.value
ma1    -0.0769 0.0109 -7.0862  0.0000
xmean   0.0004 0.0002  2.4946  0.0126

sigma^2 estimated as 0.0002713429 on 8643 degrees of freedom 
 
AIC = -5.373556  AICc = -5.373555  BIC = -5.371104 
 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>chevron.res<span class="ot">&lt;-</span>fit_chevron<span class="sc">$</span>residuals</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(chevron.res, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>plot6 <span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(chevron.res, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(plot5, plot6,<span class="at">nrow=</span><span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>plot7 <span class="ot">&lt;-</span> <span class="fu">ggAcf</span>(chevron.res<span class="sc">^</span><span class="dv">2</span>, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>plot8 <span class="ot">&lt;-</span> <span class="fu">ggPacf</span>(chevron.res<span class="sc">^</span><span class="dv">2</span>, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(plot7,plot8,<span class="at">nrow=</span><span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="method-1-garch-model-on-arima-residuals" class="level1">
<h1>8. Method 1: GARCH Model on ARIMA Residuals</h1>
<p>After determining the presence of conditional heteroskedasticity in the residuals of the ARIMA model, we proceed with fitting a GARCH model. The GARCH model is designed to model the volatility clustering evident in financial time series, allowing for more accurate forecasting of risk and volatility.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">list</span>() </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>cc <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (p <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>) {</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (q <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>) {</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">suppressWarnings</span>({</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>      model[[cc]] <span class="ot">&lt;-</span> <span class="fu">garch</span>(exxon.res, <span class="at">order=</span><span class="fu">c</span>(p,q), <span class="at">trace=</span>F)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    cc <span class="ot">&lt;-</span> cc <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="do">## get AIC values for model evaluation</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>GARCH_AIC <span class="ot">&lt;-</span> <span class="fu">sapply</span>(model, AIC) <span class="do">## model with lowest AIC is the best</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(GARCH_AIC <span class="sc">==</span> <span class="fu">min</span>(GARCH_AIC))</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>model[[<span class="fu">which</span>(GARCH_AIC <span class="sc">==</span> <span class="fu">min</span>(GARCH_AIC))]]</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
garch(x = exxon.res, order = c(p, q), trace = F)

Coefficient(s):
       a0         a1         b1  
2.446e-06  7.078e-02  9.190e-01  </code></pre>
</div>
</div>
<p>The model with the lowest AIC appears to be a GARCH (1,1). Now lets fit GARCH (1,1)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Fit the GARCH(1,1) model on the residuals</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>garch_fit_exxon <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span><span class="fu">garch</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">data =</span> exxon.res, <span class="at">trace =</span> F)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary of the fitted GARCH model</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(garch_fit_exxon)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 GARCH Modelling 

Call:
 garchFit(formula = ~garch(1, 1), data = exxon.res, trace = F) 

Mean and Variance Equation:
 data ~ garch(1, 1)
&lt;environment: 0x105022d68&gt;
 [data = exxon.res]

Conditional Distribution:
 norm 

Coefficient(s):
        mu       omega      alpha1       beta1  
2.3841e-05  2.4480e-06  7.0832e-02  9.1892e-01  

Std. Errors:
 based on Hessian 

Error Analysis:
        Estimate  Std. Error  t value Pr(&gt;|t|)    
mu     2.384e-05   1.289e-04    0.185    0.853    
omega  2.448e-06   3.988e-07    6.138 8.36e-10 ***
alpha1 7.083e-02   5.377e-03   13.173  &lt; 2e-16 ***
beta1  9.189e-01   6.110e-03  150.407  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log Likelihood:
 24997.65    normalized:  2.891574 

Description:
 Sun Apr 28 02:29:51 2024 by user:  


Standardised Residuals Tests:
                                Statistic p-Value   
 Jarque-Bera Test   R    Chi^2  664.2732  0         
 Shapiro-Wilk Test  R    W      NA        NA        
 Ljung-Box Test     R    Q(10)  20.21923  0.02724602
 Ljung-Box Test     R    Q(15)  22.61764  0.09260248
 Ljung-Box Test     R    Q(20)  32.17146  0.04150525
 Ljung-Box Test     R^2  Q(10)  20.8043   0.0225003 
 Ljung-Box Test     R^2  Q(15)  28.27121  0.01993171
 Ljung-Box Test     R^2  Q(20)  30.62473  0.06034362
 LM Arch Test       R    TR^2   24.05791  0.0199752 

Information Criterion Statistics:
      AIC       BIC       SIC      HQIC 
-5.782222 -5.778953 -5.782222 -5.781107 </code></pre>
</div>
</div>
<p>All coefficients (omega, alpha1, beta1) are highly significant. This implies that the GARCH(1,1) model captures the volatility clustering effectively.</p>
<p>The best model according to method 1 is ARIMA(1,0,1) + GARCH(1,1).</p>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">list</span>() <span class="do">## set counter</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>cc <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (p <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>) {</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (q <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>) {</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>model[[cc]] <span class="ot">&lt;-</span> <span class="fu">garch</span>(chevron.res,<span class="at">order=</span><span class="fu">c</span>(q,p),<span class="at">trace=</span>F)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>cc <span class="ot">&lt;-</span> cc <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>} </span></code></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information

Warning in garch(chevron.res, order = c(q, p), trace = F): singular information</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="do">## get AIC values for model evaluation</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>GARCH_AIC <span class="ot">&lt;-</span> <span class="fu">sapply</span>(model, AIC) <span class="do">## model with lowest AIC is the best</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(GARCH_AIC <span class="sc">==</span> <span class="fu">min</span>(GARCH_AIC))</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>model[[<span class="fu">which</span>(GARCH_AIC <span class="sc">==</span> <span class="fu">min</span>(GARCH_AIC))]]</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
garch(x = chevron.res, order = c(q, p), trace = F)

Coefficient(s):
       a0         a1         b1  
3.951e-06  7.042e-02  9.132e-01  </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">garchFit</span>(<span class="sc">~</span><span class="fu">garch</span>(<span class="dv">1</span>,<span class="dv">1</span>), chevron.res,<span class="at">trace =</span> F))</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 GARCH Modelling 

Call:
 garchFit(formula = ~garch(1, 1), data = chevron.res, trace = F) 

Mean and Variance Equation:
 data ~ garch(1, 1)
&lt;environment: 0x105513140&gt;
 [data = chevron.res]

Conditional Distribution:
 norm 

Coefficient(s):
         mu        omega       alpha1        beta1  
-3.7450e-08   3.9501e-06   7.0414e-02   9.1319e-01  

Std. Errors:
 based on Hessian 

Error Analysis:
         Estimate  Std. Error  t value Pr(&gt;|t|)    
mu     -3.745e-08   1.393e-04    0.000        1    
omega   3.950e-06   5.741e-07    6.881 5.94e-12 ***
alpha1  7.041e-02   5.254e-03   13.402  &lt; 2e-16 ***
beta1   9.132e-01   6.489e-03  140.719  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log Likelihood:
 24533.25    normalized:  2.837854 

Description:
 Sun Apr 28 02:29:52 2024 by user:  


Standardised Residuals Tests:
                                Statistic p-Value     
 Jarque-Bera Test   R    Chi^2  979.4904  0           
 Shapiro-Wilk Test  R    W      NA        NA          
 Ljung-Box Test     R    Q(10)  35.03331  0.0001232413
 Ljung-Box Test     R    Q(15)  39.04061  0.0006319607
 Ljung-Box Test     R    Q(20)  50.24906  0.0002040023
 Ljung-Box Test     R^2  Q(10)  18.43982  0.04798249  
 Ljung-Box Test     R^2  Q(15)  19.64699  0.1858966   
 Ljung-Box Test     R^2  Q(20)  26.45813  0.1512086   
 LM Arch Test       R    TR^2   18.51565  0.100907    

Information Criterion Statistics:
      AIC       BIC       SIC      HQIC 
-5.674783 -5.671514 -5.674784 -5.673669 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="method-2-garch-model" class="level1">
<h1>9. Method 2: GARCH Model</h1>
<p>The GARCH model is designed to model the volatility clustering evident in financial time series, allowing for more accurate forecasting of risk and volatility. Here we will fit the model on the returns</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">list</span>() </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>cc <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (p <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>) {</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (q <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>) {</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">suppressWarnings</span>({</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>      model[[cc]] <span class="ot">&lt;-</span> <span class="fu">garch</span>(returns_exxon, <span class="at">order=</span><span class="fu">c</span>(p,q), <span class="at">trace=</span>F)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>    cc <span class="ot">&lt;-</span> cc <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="do">## get AIC values for model evaluation</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>GARCH_AIC <span class="ot">&lt;-</span> <span class="fu">sapply</span>(model, AIC) <span class="do">## model with lowest AIC is the best</span></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(GARCH_AIC <span class="sc">==</span> <span class="fu">min</span>(GARCH_AIC))</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>model[[<span class="fu">which</span>(GARCH_AIC <span class="sc">==</span> <span class="fu">min</span>(GARCH_AIC))]]</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
garch(x = returns_exxon, order = c(p, q), trace = F)

Coefficient(s):
       a0         a1         b1  
2.387e-06  6.937e-02  9.207e-01  </code></pre>
</div>
</div>
<p>GARCH(1,1) model has the lowest AIC.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>garch_fit_returns_exxon <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span><span class="fu">garch</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">data =</span> returns_exxon, <span class="at">trace =</span> F)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(garch_fit_returns_exxon)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 GARCH Modelling 

Call:
 garchFit(formula = ~garch(1, 1), data = returns_exxon, trace = F) 

Mean and Variance Equation:
 data ~ garch(1, 1)
&lt;environment: 0x12b3ec000&gt;
 [data = returns_exxon]

Conditional Distribution:
 norm 

Coefficient(s):
        mu       omega      alpha1       beta1  
5.1878e-04  2.4184e-06  7.0484e-02  9.1945e-01  

Std. Errors:
 based on Hessian 

Error Analysis:
        Estimate  Std. Error  t value Pr(&gt;|t|)    
mu     5.188e-04   1.277e-04    4.064 4.83e-05 ***
omega  2.418e-06   3.965e-07    6.100 1.06e-09 ***
alpha1 7.048e-02   5.335e-03   13.213  &lt; 2e-16 ***
beta1  9.195e-01   6.050e-03  151.980  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log Likelihood:
 24975.39    normalized:  2.888998 

Description:
 Sun Apr 28 02:29:55 2024 by user:  


Standardised Residuals Tests:
                                Statistic p-Value    
 Jarque-Bera Test   R    Chi^2  618.5361  0          
 Shapiro-Wilk Test  R    W      NA        NA         
 Ljung-Box Test     R    Q(10)  28.25277  0.001644409
 Ljung-Box Test     R    Q(15)  31.10346  0.008509004
 Ljung-Box Test     R    Q(20)  41.97728  0.0027845  
 Ljung-Box Test     R^2  Q(10)  21.13785  0.02015259 
 Ljung-Box Test     R^2  Q(15)  28.7468   0.01733528 
 Ljung-Box Test     R^2  Q(20)  31.14756  0.05327235 
 LM Arch Test       R    TR^2   24.2292   0.01892881 

Information Criterion Statistics:
      AIC       BIC       SIC      HQIC 
-5.777071 -5.773802 -5.777071 -5.775957 </code></pre>
</div>
</div>
<p>All parameters in the model are statistically significant, as indicated by the p-values being less than 0.05.</p>
<p>Thus for method 2 fitting GARCH(1,1) model directly to the returns of Exxon Mobil is the best model.</p>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">

</div>
</div>
</div>
</section>
<section id="model-diagnostics" class="level1">
<h1>10. Model Diagnostics</h1>
<p>Now lets do Model Diagnostics for both the models selected in Method 1 and Method 2 above</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-11-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-1" role="tab" aria-controls="tabset-11-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-2" role="tab" aria-controls="tabset-11-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-11-1-tab">
<section id="method-1-arima101-garch11" class="level3">
<h3 class="anchored" data-anchor-id="method-1-arima101-garch11">Method 1: ARIMA(1,0,1) + GARCH(1,1)</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_exxon)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Series: returns_exxon 
ARIMA(1,0,1) with non-zero mean 

Coefficients:
         ar1      ma1   mean
      0.5315  -0.6136  4e-04
s.e.  0.0723   0.0673  1e-04

sigma^2 = 0.000244:  log likelihood = 23690.52
AIC=-47373.03   AICc=-47373.03   BIC=-47344.77

Training set error measures:
                        ME       RMSE        MAE MPE MAPE      MASE        ACF1
Training set -2.384065e-06 0.01561831 0.01100162 NaN  Inf 0.6700628 0.001893208</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>garch_exxon <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span><span class="fu">garch</span>(<span class="dv">1</span>,<span class="dv">1</span>), exxon.res,<span class="at">trace =</span> F)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(garch_exxon)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 GARCH Modelling 

Call:
 garchFit(formula = ~garch(1, 1), data = exxon.res, trace = F) 

Mean and Variance Equation:
 data ~ garch(1, 1)
&lt;environment: 0x12af0c600&gt;
 [data = exxon.res]

Conditional Distribution:
 norm 

Coefficient(s):
        mu       omega      alpha1       beta1  
2.3841e-05  2.4480e-06  7.0832e-02  9.1892e-01  

Std. Errors:
 based on Hessian 

Error Analysis:
        Estimate  Std. Error  t value Pr(&gt;|t|)    
mu     2.384e-05   1.289e-04    0.185    0.853    
omega  2.448e-06   3.988e-07    6.138 8.36e-10 ***
alpha1 7.083e-02   5.377e-03   13.173  &lt; 2e-16 ***
beta1  9.189e-01   6.110e-03  150.407  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log Likelihood:
 24997.65    normalized:  2.891574 

Description:
 Sun Apr 28 02:29:56 2024 by user:  


Standardised Residuals Tests:
                                Statistic p-Value   
 Jarque-Bera Test   R    Chi^2  664.2732  0         
 Shapiro-Wilk Test  R    W      NA        NA        
 Ljung-Box Test     R    Q(10)  20.21923  0.02724602
 Ljung-Box Test     R    Q(15)  22.61764  0.09260248
 Ljung-Box Test     R    Q(20)  32.17146  0.04150525
 Ljung-Box Test     R^2  Q(10)  20.8043   0.0225003 
 Ljung-Box Test     R^2  Q(15)  28.27121  0.01993171
 Ljung-Box Test     R^2  Q(20)  30.62473  0.06034362
 LM Arch Test       R    TR^2   24.05791  0.0199752 

Information Criterion Statistics:
      AIC       BIC       SIC      HQIC 
-5.782222 -5.778953 -5.782222 -5.781107 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">garch</span>(exxon.res, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">trace =</span> F))</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
garch(x = exxon.res, order = c(1, 1), trace = F)

Model:
GARCH(1,1)

Residuals:
      Min        1Q    Median        3Q       Max 
-5.626293 -0.615750  0.008538  0.627444  5.340125 

Coefficient(s):
    Estimate  Std. Error  t value Pr(&gt;|t|)    
a0 2.446e-06   2.799e-07    8.736   &lt;2e-16 ***
a1 7.078e-02   3.487e-03   20.294   &lt;2e-16 ***
b1 9.190e-01   3.896e-03  235.891   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Diagnostic Tests:
    Jarque Bera Test

data:  Residuals
X-squared = 664.87, df = 2, p-value &lt; 2.2e-16


    Box-Ljung test

data:  Squared.Residuals
X-squared = 4.6787, df = 1, p-value = 0.03054</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">checkresiduals</span>(<span class="fu">garch</span>(exxon.res, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">trace =</span> F))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals
Q* = 778.16, df = 730.5, p-value = 0.1078

Model df: 0.   Total lags used: 730.5</code></pre>
</div>
</div>
<p>The residuals do not show any obvious trends or seasonality, which suggests that the ARIMA model has captured the linear structure of the data. However, there are some visible outliers. Residuals are normally distributed, which supports one of the underlying assumptions of the ARIMA model.</p>
<p>The Ljung-Box test on residuals with a p-value of 0.1078 suggests that there is no significant autocorrelation in the residuals. This implies that the model residuals are random.</p>
<p>The coefficients of the GARCH(1,1) model are all statistically significant.</p>
</section>
<section id="method-2-garch11" class="level3">
<h3 class="anchored" data-anchor-id="method-2-garch11">Method 2: GARCH(1,1)</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>garch_returns_exxon1 <span class="ot">&lt;-</span> <span class="fu">garch</span>(returns_exxon, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">trace =</span> F)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(garch_returns_exxon1)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
garch(x = returns_exxon, order = c(1, 1), trace = F)

Model:
GARCH(1,1)

Residuals:
     Min       1Q   Median       3Q      Max 
-5.43624 -0.59095  0.01182  0.65548  5.29900 

Coefficient(s):
    Estimate  Std. Error  t value Pr(&gt;|t|)    
a0 2.387e-06   2.776e-07    8.599   &lt;2e-16 ***
a1 6.937e-02   3.475e-03   19.964   &lt;2e-16 ***
b1 9.207e-01   3.887e-03  236.859   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Diagnostic Tests:
    Jarque Bera Test

data:  Residuals
X-squared = 631.51, df = 2, p-value &lt; 2.2e-16


    Box-Ljung test

data:  Squared.Residuals
X-squared = 2.5949, df = 1, p-value = 0.1072</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">checkresiduals</span>(garch_returns_exxon1)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals
Q* = 778.36, df = 730.5, p-value = 0.1069

Model df: 0.   Total lags used: 730.5</code></pre>
</div>
</div>
<p>The estimated GARCH(1,1) model coefficients are statistically significant.</p>
<p>The p-value from the Ljung-Box test suggests that there’s no significant autocorrelation in the residuals.</p>
</section>
</div>
<div id="tabset-11-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-2-tab">

</div>
</div>
</div>
</section>
<section id="cross-validation" class="level1">
<h1>11. Cross-Validation</h1>
<p>Cross-validation is an essential technique in model validation, which helps to ensure that the results of our time series analysis generalize to independent data sets. Now lets do cross-validation</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-12-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-1" role="tab" aria-controls="tabset-12-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-2" role="tab" aria-controls="tabset-12-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-12-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">900</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(returns_exxon)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>err1 <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>err2 <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(n<span class="sc">-</span>k)) {</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  xtrain <span class="ot">&lt;-</span> returns_exxon[<span class="dv">1</span><span class="sc">:</span>(k<span class="dv">-1</span>)<span class="sc">+</span>i]</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>  xtest <span class="ot">&lt;-</span> returns_exxon[k<span class="sc">+</span>i]</span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ARIMA(1,0,1) + GARCH(1,1)</span></span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a>  arima.fit <span class="ot">&lt;-</span> <span class="fu">Arima</span>(xtrain, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="at">include.drift =</span> <span class="cn">TRUE</span>)</span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a>  arima.res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima.fit)</span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a>  fit1 <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span><span class="fu">garch</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">data =</span> arima.res, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a>  fcast1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit1, <span class="at">n.ahead =</span> <span class="dv">1</span>)</span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb78-17"><a href="#cb78-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># GARCH(1,1)</span></span>
<span id="cb78-18"><a href="#cb78-18" aria-hidden="true" tabindex="-1"></a>  returns_diff <span class="ot">&lt;-</span> <span class="fu">diff</span>(xtrain)  </span>
<span id="cb78-19"><a href="#cb78-19" aria-hidden="true" tabindex="-1"></a>  fit2 <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span><span class="fu">garch</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">data =</span> xtrain, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb78-20"><a href="#cb78-20" aria-hidden="true" tabindex="-1"></a>  fcast2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit2, <span class="at">n.ahead =</span> <span class="dv">1</span>)</span>
<span id="cb78-21"><a href="#cb78-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb78-22"><a href="#cb78-22" aria-hidden="true" tabindex="-1"></a>  err1 <span class="ot">&lt;-</span> <span class="fu">c</span>(err1, (fcast1<span class="sc">$</span>meanForecast <span class="sc">-</span> xtest)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb78-23"><a href="#cb78-23" aria-hidden="true" tabindex="-1"></a>  err2 <span class="ot">&lt;-</span> <span class="fu">c</span>(err2, (fcast2<span class="sc">$</span>meanForecast <span class="sc">-</span> xtest)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb78-24"><a href="#cb78-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb78-25"><a href="#cb78-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-26"><a href="#cb78-26" aria-hidden="true" tabindex="-1"></a>RMSE1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(err1))</span>
<span id="cb78-27"><a href="#cb78-27" aria-hidden="true" tabindex="-1"></a>RMSE2 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(err2))</span></code></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The RMSE for model 1 -"</span>, RMSE1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The RMSE for model 1 - 0.01608689 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The RMSE for model 2 -"</span>, RMSE2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The RMSE for model 2 - 0.01608936 </code></pre>
</div>
</div>
<p>After performing cross-validation, we can see that Model 1 had slighlty lowest RMSE. Therefore, the best model according to diagnostics is Model 1: ARIMA(1,0,1) + GARCH(1,1)</p>
</div>
<div id="tabset-12-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-2-tab">

</div>
</div>
</div>
</section>
<section id="final-model" class="level1">
<h1>12. Final Model</h1>
<p>Now I will fit the model with best performance</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-13-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-1" role="tab" aria-controls="tabset-13-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-13-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-2" role="tab" aria-controls="tabset-13-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-13-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Fit the ARIMA model</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>arima_exxon_final <span class="ot">&lt;-</span> <span class="fu">Arima</span>(returns_exxon, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Extract the residuals</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>residuals_exxon_final <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arima_exxon_final)</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the GARCH model on the residuals</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>garch_exxon_final <span class="ot">&lt;-</span> <span class="fu">garchFit</span>(<span class="sc">~</span><span class="fu">garch</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">data =</span> residuals_exxon_final, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(garch_exxon_final)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 GARCH Modelling 

Call:
 garchFit(formula = ~garch(1, 1), data = residuals_exxon_final, 
    trace = FALSE) 

Mean and Variance Equation:
 data ~ garch(1, 1)
&lt;environment: 0x12be5ec30&gt;
 [data = residuals_exxon_final]

Conditional Distribution:
 norm 

Coefficient(s):
        mu       omega      alpha1       beta1  
2.3841e-05  2.4480e-06  7.0832e-02  9.1892e-01  

Std. Errors:
 based on Hessian 

Error Analysis:
        Estimate  Std. Error  t value Pr(&gt;|t|)    
mu     2.384e-05   1.289e-04    0.185    0.853    
omega  2.448e-06   3.988e-07    6.138 8.36e-10 ***
alpha1 7.083e-02   5.377e-03   13.173  &lt; 2e-16 ***
beta1  9.189e-01   6.110e-03  150.407  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log Likelihood:
 24997.65    normalized:  2.891574 

Description:
 Sun Apr 28 02:36:30 2024 by user:  


Standardised Residuals Tests:
                                Statistic p-Value   
 Jarque-Bera Test   R    Chi^2  664.2732  0         
 Shapiro-Wilk Test  R    W      NA        NA        
 Ljung-Box Test     R    Q(10)  20.21923  0.02724602
 Ljung-Box Test     R    Q(15)  22.61764  0.09260248
 Ljung-Box Test     R    Q(20)  32.17146  0.04150525
 Ljung-Box Test     R^2  Q(10)  20.8043   0.0225003 
 Ljung-Box Test     R^2  Q(15)  28.27121  0.01993171
 Ljung-Box Test     R^2  Q(20)  30.62473  0.06034362
 LM Arch Test       R    TR^2   24.05791  0.0199752 

Information Criterion Statistics:
      AIC       BIC       SIC      HQIC 
-5.782222 -5.778953 -5.782222 -5.781107 </code></pre>
</div>
</div>
<ul>
<li>All the coefficients are significant</li>
<li>The log likelihood of the model is 24997.66, suggesting a very good fit to the data.</li>
<li>The information criteria values (AIC, BIC, SIC, HQIC) are extremely low.</li>
<li>Ljung-Box Tests on Residuals and Squared Residuals: These indicate some autocorrelation in residuals</li>
</ul>
<p>The ARIMA(1,0,1) + GARCH(1,1) effectively captures the volatility dynamics in Exxon Mobil’s stock returns.</p>
</div>
<div id="tabset-13-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-13-2-tab">

</div>
</div>
</div>
</section>
<section id="forecasting-with-the-final-model" class="level1">
<h1>13. Forecasting with the Final Model</h1>
<p>Now I would use the final model to forecast the future trends</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-14-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-14-1" role="tab" aria-controls="tabset-14-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-14-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-14-2" role="tab" aria-controls="tabset-14-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-14-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-14-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(garch_exxon_final, <span class="at">n.ahead =</span> <span class="dv">100</span>, <span class="at">plot =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    meanForecast  meanError standardDeviation lowerInterval upperInterval
1   2.384065e-05 0.01155372        0.01155372   -0.02262104    0.02266872
2   2.384065e-05 0.01160034        0.01160034   -0.02271241    0.02276010
3   2.384065e-05 0.01164630        0.01164630   -0.02280249    0.02285017
4   2.384065e-05 0.01169161        0.01169161   -0.02289129    0.02293897
5   2.384065e-05 0.01173628        0.01173628   -0.02297885    0.02302653
6   2.384065e-05 0.01178033        0.01178033   -0.02306518    0.02311286
7   2.384065e-05 0.01182376        0.01182376   -0.02315031    0.02319799
8   2.384065e-05 0.01186659        0.01186659   -0.02323426    0.02328194
9   2.384065e-05 0.01190884        0.01190884   -0.02331705    0.02336473
10  2.384065e-05 0.01195050        0.01195050   -0.02339870    0.02344638
11  2.384065e-05 0.01199159        0.01199159   -0.02347924    0.02352692
12  2.384065e-05 0.01203212        0.01203212   -0.02355868    0.02360636
13  2.384065e-05 0.01207210        0.01207210   -0.02363705    0.02368473
14  2.384065e-05 0.01211155        0.01211155   -0.02371435    0.02376203
15  2.384065e-05 0.01215046        0.01215046   -0.02379062    0.02383830
16  2.384065e-05 0.01218885        0.01218885   -0.02386586    0.02391355
17  2.384065e-05 0.01222673        0.01222673   -0.02394010    0.02398779
18  2.384065e-05 0.01226410        0.01226410   -0.02401336    0.02406104
19  2.384065e-05 0.01230098        0.01230098   -0.02408564    0.02413332
20  2.384065e-05 0.01233738        0.01233738   -0.02415697    0.02420465
21  2.384065e-05 0.01237329        0.01237329   -0.02422736    0.02427505
22  2.384065e-05 0.01240874        0.01240874   -0.02429683    0.02434452
23  2.384065e-05 0.01244372        0.01244372   -0.02436540    0.02441308
24  2.384065e-05 0.01247824        0.01247824   -0.02443307    0.02448075
25  2.384065e-05 0.01251232        0.01251232   -0.02449986    0.02454754
26  2.384065e-05 0.01254596        0.01254596   -0.02456579    0.02461347
27  2.384065e-05 0.01257917        0.01257917   -0.02463087    0.02467855
28  2.384065e-05 0.01261194        0.01261194   -0.02469511    0.02474280
29  2.384065e-05 0.01264430        0.01264430   -0.02475854    0.02480622
30  2.384065e-05 0.01267625        0.01267625   -0.02482115    0.02486883
31  2.384065e-05 0.01270779        0.01270779   -0.02488296    0.02493064
32  2.384065e-05 0.01273892        0.01273892   -0.02494399    0.02499167
33  2.384065e-05 0.01276967        0.01276967   -0.02500425    0.02505193
34  2.384065e-05 0.01280003        0.01280003   -0.02506375    0.02511143
35  2.384065e-05 0.01283000        0.01283000   -0.02512250    0.02517018
36  2.384065e-05 0.01285960        0.01285960   -0.02518051    0.02522819
37  2.384065e-05 0.01288883        0.01288883   -0.02523780    0.02528548
38  2.384065e-05 0.01291769        0.01291769   -0.02529437    0.02534205
39  2.384065e-05 0.01294620        0.01294620   -0.02535024    0.02539792
40  2.384065e-05 0.01297435        0.01297435   -0.02540541    0.02545309
41  2.384065e-05 0.01300215        0.01300215   -0.02545990    0.02550758
42  2.384065e-05 0.01302961        0.01302961   -0.02551372    0.02556140
43  2.384065e-05 0.01305673        0.01305673   -0.02556687    0.02561455
44  2.384065e-05 0.01308351        0.01308351   -0.02561937    0.02566705
45  2.384065e-05 0.01310997        0.01310997   -0.02567123    0.02571891
46  2.384065e-05 0.01313610        0.01313610   -0.02572245    0.02577013
47  2.384065e-05 0.01316192        0.01316192   -0.02577305    0.02582073
48  2.384065e-05 0.01318742        0.01318742   -0.02582303    0.02587071
49  2.384065e-05 0.01321261        0.01321261   -0.02587240    0.02592008
50  2.384065e-05 0.01323750        0.01323750   -0.02592118    0.02596886
51  2.384065e-05 0.01326208        0.01326208   -0.02596936    0.02601704
52  2.384065e-05 0.01328637        0.01328637   -0.02601696    0.02606464
53  2.384065e-05 0.01331036        0.01331036   -0.02606399    0.02611167
54  2.384065e-05 0.01333407        0.01333407   -0.02611045    0.02615814
55  2.384065e-05 0.01335749        0.01335749   -0.02615636    0.02620404
56  2.384065e-05 0.01338063        0.01338063   -0.02620172    0.02624940
57  2.384065e-05 0.01340350        0.01340350   -0.02624653    0.02629421
58  2.384065e-05 0.01342609        0.01342609   -0.02629081    0.02633849
59  2.384065e-05 0.01344841        0.01344841   -0.02633456    0.02638224
60  2.384065e-05 0.01347047        0.01347047   -0.02637780    0.02642548
61  2.384065e-05 0.01349227        0.01349227   -0.02642052    0.02646820
62  2.384065e-05 0.01351380        0.01351380   -0.02646273    0.02651041
63  2.384065e-05 0.01353509        0.01353509   -0.02650444    0.02655213
64  2.384065e-05 0.01355612        0.01355612   -0.02654567    0.02659335
65  2.384065e-05 0.01357690        0.01357690   -0.02658640    0.02663409
66  2.384065e-05 0.01359745        0.01359745   -0.02662666    0.02667434
67  2.384065e-05 0.01361774        0.01361774   -0.02666645    0.02671413
68  2.384065e-05 0.01363781        0.01363781   -0.02670577    0.02675345
69  2.384065e-05 0.01365763        0.01365763   -0.02674463    0.02679231
70  2.384065e-05 0.01367723        0.01367723   -0.02678303    0.02683071
71  2.384065e-05 0.01369659        0.01369659   -0.02682099    0.02686867
72  2.384065e-05 0.01371574        0.01371574   -0.02685851    0.02690619
73  2.384065e-05 0.01373465        0.01373465   -0.02689559    0.02694327
74  2.384065e-05 0.01375335        0.01375335   -0.02693224    0.02697992
75  2.384065e-05 0.01377184        0.01377184   -0.02696846    0.02701614
76  2.384065e-05 0.01379010        0.01379010   -0.02700427    0.02705195
77  2.384065e-05 0.01380816        0.01380816   -0.02703966    0.02708734
78  2.384065e-05 0.01382601        0.01382601   -0.02707464    0.02712232
79  2.384065e-05 0.01384365        0.01384365   -0.02710922    0.02715690
80  2.384065e-05 0.01386109        0.01386109   -0.02714340    0.02719109
81  2.384065e-05 0.01387833        0.01387833   -0.02717719    0.02722487
82  2.384065e-05 0.01389538        0.01389538   -0.02721060    0.02725828
83  2.384065e-05 0.01391222        0.01391222   -0.02724361    0.02729130
84  2.384065e-05 0.01392888        0.01392888   -0.02727626    0.02732394
85  2.384065e-05 0.01394534        0.01394534   -0.02730852    0.02735621
86  2.384065e-05 0.01396162        0.01396162   -0.02734042    0.02738811
87  2.384065e-05 0.01397771        0.01397771   -0.02737196    0.02741964
88  2.384065e-05 0.01399361        0.01399361   -0.02740314    0.02745082
89  2.384065e-05 0.01400934        0.01400934   -0.02743396    0.02748164
90  2.384065e-05 0.01402489        0.01402489   -0.02746444    0.02751212
91  2.384065e-05 0.01404026        0.01404026   -0.02749456    0.02754224
92  2.384065e-05 0.01405546        0.01405546   -0.02752435    0.02757203
93  2.384065e-05 0.01407048        0.01407048   -0.02755380    0.02760148
94  2.384065e-05 0.01408534        0.01408534   -0.02758291    0.02763059
95  2.384065e-05 0.01410003        0.01410003   -0.02761170    0.02765938
96  2.384065e-05 0.01411455        0.01411455   -0.02764016    0.02768785
97  2.384065e-05 0.01412891        0.01412891   -0.02766831    0.02771599
98  2.384065e-05 0.01414310        0.01414310   -0.02769613    0.02774381
99  2.384065e-05 0.01415714        0.01415714   -0.02772364    0.02777133
100 2.384065e-05 0.01417102        0.01417102   -0.02775085    0.02779853</code></pre>
</div>
</div>
<p>Future will be similar but with higher uncertainty because of the bigger confidence intervals.</p>
</div>
<div id="tabset-14-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-14-2-tab">

</div>
</div>
</div>
</section>
<section id="volatility-plot" class="level1">
<h1>14. Volatility Plot</h1>
<p>In this section, we will look at the volatility dynamics of stock price as captured by our final model</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-15-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-15-1" role="tab" aria-controls="tabset-15-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-15-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-15-2" role="tab" aria-controls="tabset-15-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-15-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-15-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>ht <span class="ot">&lt;-</span> garch_exxon_final<span class="sc">@</span>h.t </span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>exxon_stockprice_df <span class="ot">=</span> <span class="fu">data.frame</span>(Exxon_stockprice)</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>exxon_stockprice_df <span class="ot">&lt;-</span> <span class="fu">head</span>(exxon_stockprice_df, <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>exxon_stockprice_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(exxon_stockprice_df,<span class="fu">rownames</span>(exxon_stockprice_df))</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(exxon_stockprice_df)[<span class="dv">7</span>] <span class="ot">=</span> <span class="st">"date"</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>exxon_stockprice_df<span class="sc">$</span>date<span class="ot">&lt;-</span><span class="fu">as.Date</span>(exxon_stockprice_df<span class="sc">$</span>date,<span class="st">"%Y-%m-%d"</span>)</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>data_spot <span class="ot">=</span> <span class="fu">data.frame</span>(ht,exxon_stockprice_df<span class="sc">$</span>date)</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_spot, <span class="fu">aes</span>(<span class="at">y =</span> ht, <span class="at">x =</span> exxon_stockprice_df.date)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">'Conditional Variance'</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">'Date'</span>) <span class="sc">+</span></span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Volatility plot for Exxon Mobil Stock Price"</span>) <span class="sc">+</span></span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="financial-ts-models_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the graph, we observe periods with peaks indicating heightened volatility, esp around 2008-2009 and then after 2020.</p>
</div>
<div id="tabset-15-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-15-2-tab">

</div>
</div>
</div>
</section>
<section id="model-equations" class="level1">
<h1>15. Model Equations</h1>
<p>Finally the model equation based on the best model</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-16-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-16-1" role="tab" aria-controls="tabset-16-1" aria-selected="true">Exxon Mobil</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-16-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-16-2" role="tab" aria-controls="tabset-16-2" aria-selected="false">Chevron Corporation</a></li></ul>
<div class="tab-content">
<div id="tabset-16-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-16-1-tab">
<p>The best performing model was ARIMA(1,0,1) + GARCH(1,1). The model equation is as follows:</p>
<p><strong>ARIMA(1,0,1)</strong> equation:</p>
<p><span class="math display">\[
(1 - \phi_{B})Y_{t} = (1 + \phi_{B})\epsilon_{t}
\]</span></p>
<p><strong>GARCH(1,1)</strong> equation:</p>
<p><span class="math display">\[
\sigma_{t}^{2} = \alpha_{0} + \alpha_{1}\epsilon^{2}_{t-1}+\beta_{1}\sigma^{2}_{t-1}
\]</span></p>
</div>
<div id="tabset-16-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-16-2-tab">

</div>
</div>
</div>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>